"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Check, Clipboard, Code2, ExternalLink, Github, Plus, Sparkles } from "lucide-react";
import { useState } from "react";

import { PageHeader } from "@/components/app-shell";
import { useAuth } from "@/components/auth-provider";
import { ProjectRequired } from "@/components/project-required";
import { apiRequest } from "@/lib/api";
import type { PortfolioProject } from "@/lib/types";

export default function PortfolioReviewPage() {
  const { user } = useAuth();
  const projectId = user?.active_project_id;
  const queryClient = useQueryClient();
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ name: "", description: "", github_url: "", live_url: "", tech_stack: "" });
  const projects = useQuery({ queryKey: ["portfolio-projects", projectId], queryFn: () => apiRequest<PortfolioProject[]>(`/portfolio-projects?project_id=${projectId}`), enabled: Boolean(projectId) });
  const create = useMutation({
    mutationFn: () => apiRequest<PortfolioProject>("/portfolio-projects", { method: "POST", body: JSON.stringify({ project_id: projectId, name: form.name, description: form.description, github_url: form.github_url || null, live_url: form.live_url || null, tech_stack: form.tech_stack.split(",").map((item) => item.trim()).filter(Boolean) }) }),
    onSuccess: (project) => { queryClient.setQueryData<PortfolioProject[]>(["portfolio-projects", projectId], (current = []) => [project, ...current]); setShowForm(false); setForm({ name: "", description: "", github_url: "", live_url: "", tech_stack: "" }); },
  });
  const updateCached = (project: PortfolioProject) => queryClient.setQueryData<PortfolioProject[]>(["portfolio-projects", projectId], (current = []) => current.map((item) => item.id === project.id ? project : item));
  const audit = useMutation({ mutationFn: (id: string) => apiRequest<PortfolioProject>(`/portfolio-projects/${id}/audit`, { method: "POST" }), onSuccess: updateCached });
  const prompt = useMutation({ mutationFn: (id: string) => apiRequest<PortfolioProject>(`/portfolio-projects/${id}/codex-prompt`, { method: "POST" }), onSuccess: updateCached });
  return <><PageHeader eyebrow="Make your work easier to trust" title="Portfolio review" description="Audit the presentation around your real projects, then generate a Codex-ready improvement prompt that explicitly refuses invented features or metrics." action={<button className="inline-flex items-center gap-2 rounded-xl bg-[#5b4df5] px-4 py-2.5 text-sm font-semibold text-white" onClick={() => setShowForm(true)}><Plus className="size-4" />Add project</button>} />{!projectId ? <ProjectRequired /> : <>{showForm && <form className="mt-7 rounded-3xl border border-[#dcd9ff] bg-white p-6" onSubmit={(event) => { event.preventDefault(); create.mutate(); }}><h2 className="font-semibold">Add a real project</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Project name" value={form.name} onChange={(value) => setForm({ ...form, name: value })} placeholder="Developer workflow tool" required /><Field label="Tech stack · comma separated" value={form.tech_stack} onChange={(value) => setForm({ ...form, tech_stack: value })} placeholder="Next.js, FastAPI, PostgreSQL" /><Field label="GitHub URL" type="url" value={form.github_url} onChange={(value) => setForm({ ...form, github_url: value })} placeholder="https://github.com/…" /><Field label="Live URL" type="url" value={form.live_url} onChange={(value) => setForm({ ...form, live_url: value })} placeholder="https://…" /></div><label className="mt-4 block text-sm font-semibold">What the project actually does<textarea className="mt-2 min-h-28 w-full rounded-xl border border-[#d0d5dd] px-4 py-3 font-normal" minLength={10} onChange={(event) => setForm({ ...form, description: event.target.value })} required value={form.description} /></label><div className="mt-5 flex justify-end gap-2"><button className="px-4 py-2 text-sm font-semibold text-[#667085]" onClick={() => setShowForm(false)} type="button">Cancel</button><button className="rounded-xl bg-[#172033] px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50" disabled={create.isPending}>Save project</button></div>{create.error && <p className="mt-3 text-sm text-red-600">{create.error.message}</p>}</form>}<section className="mt-7 grid gap-5 xl:grid-cols-2">{projects.data?.map((project) => <ProjectCard audit={() => audit.mutate(project.id)} key={project.id} makePrompt={() => prompt.mutate(project.id)} project={project} />)}{!projects.data?.length && <button className="rounded-3xl border border-dashed border-[#cfd3dc] bg-white p-14 text-center xl:col-span-2" onClick={() => setShowForm(true)}><Code2 className="mx-auto size-8 text-[#8c83f7]" /><span className="mt-4 block font-semibold">Add the project you want employers to notice</span><span className="mt-2 block text-sm text-[#667085]">Start with its real purpose, links, and technology choices.</span></button>}</section></>}</>;
}

function ProjectCard({ project, audit, makePrompt }: { project: PortfolioProject; audit: () => void; makePrompt: () => void }) {
  const [copied, setCopied] = useState(false);
  const copyPrompt = async () => { if (!project.codex_prompt) return; await navigator.clipboard.writeText(project.codex_prompt); setCopied(true); window.setTimeout(() => setCopied(false), 1500); };
  return <article className="rounded-3xl border border-[#e4e7ec] bg-white p-6"><div className="flex items-start justify-between gap-4"><div><h2 className="text-lg font-semibold">{project.name}</h2><p className="mt-2 text-sm leading-6 text-[#667085]">{project.description}</p></div><div className="flex gap-2">{project.github_url && <a href={project.github_url} rel="noreferrer" target="_blank"><Github className="size-5 text-[#667085]" /></a>}{project.live_url && <a href={project.live_url} rel="noreferrer" target="_blank"><ExternalLink className="size-5 text-[#667085]" /></a>}</div></div><div className="mt-4 flex flex-wrap gap-2">{project.tech_stack.map((tech) => <span className="rounded-full bg-[#f2f4f7] px-3 py-1 text-xs font-semibold text-[#475467]" key={tech}>{tech}</span>)}</div>{project.improvement_tasks.length ? <div className="mt-6"><p className="text-xs font-bold uppercase tracking-wider text-[#667085]">Improvement checklist</p><ul className="mt-3 space-y-2">{project.improvement_tasks.map((task) => <li className="flex items-start gap-2 text-sm text-[#475467]" key={task.title}><span className={`mt-0.5 rounded-full px-2 py-0.5 text-[10px] font-bold uppercase ${task.priority === "high" ? "bg-[#fff0e8] text-[#b54708]" : "bg-[#eeecff] text-[#5b4df5]"}`}>{task.priority}</span>{task.title}</li>)}</ul></div> : null}{project.codex_prompt && <div className="mt-5 rounded-2xl bg-[#182036] p-4 text-white"><p className="text-xs font-bold uppercase tracking-wider text-[#9c94ff]">Codex-ready prompt</p><p className="mt-2 line-clamp-4 whitespace-pre-wrap text-xs leading-5 text-[#c7cddb]">{project.codex_prompt}</p><button className="mt-3 inline-flex items-center gap-1.5 text-xs font-semibold" onClick={copyPrompt}>{copied ? <Check className="size-3.5 text-[#77e4ba]" /> : <Clipboard className="size-3.5" />}{copied ? "Copied" : "Copy prompt"}</button></div>}<div className="mt-6 flex gap-2 border-t border-[#edf0f3] pt-4"><button className="inline-flex items-center gap-2 rounded-xl border border-[#d0d5dd] px-4 py-2 text-sm font-semibold" onClick={audit}><Sparkles className="size-4" />{project.improvement_tasks.length ? "Refresh audit" : "Audit presentation"}</button><button className="rounded-xl bg-[#eeecff] px-4 py-2 text-sm font-semibold text-[#4b3ed0]" onClick={makePrompt}>Generate Codex prompt</button></div></article>;
}

function Field({ label, value, onChange, placeholder, required, type = "text" }: { label: string; value: string; onChange: (value: string) => void; placeholder: string; required?: boolean; type?: string }) {
  return <label className="text-sm font-semibold">{label}<input className="mt-2 w-full rounded-xl border border-[#d0d5dd] px-4 py-3 font-normal" onChange={(event) => onChange(event.target.value)} placeholder={placeholder} required={required} type={type} value={value} /></label>;
}
